services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "test"
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "rootsecret"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
    ports:
      - "3306:3306"
